export const tables = [
  {
    id: 1,
    table_name: "Employee Data Table",
    table_definition: {
      columns: [
        {
          id: 1,
          name: "employeeId",
          type: "text",
          header: "Employee ID",
          filter: true,
          sortable: true,
        },
        {
          id: 2,
          name: "firstName",
          type: "text",
          header: "First Name",
          filter: true,
          sortable: true,
        },
        {
          id: 3,
          name: "lastName",
          type: "text",
          header: "Last Name",
          filter: true,
          sortable: true,
        },
        {
          id: 4,
          name: "email",
          type: "email",
          header: "Email",
          filter: true,
          sortable: true,
        },
        {
          id: 5,
          name: "phone",
          type: "text",
          header: "Phone Number",
          filter: true,
          sortable: true,
        },
        {
          id: 6,
          name: "hireDate",
          type: "date",
          header: "Hire Date",
          filter: true,
          sortable: true,
        },
        {
          id: 7,
          name: "department",
          type: "text",
          header: "Department",
          filter: true,
          sortable: true,
        },
        { id: 8, name: "actions", type: "actions", header: "Actions" },
      ],
    },
    data: [
      {
        employeeId: "E001",
        firstName: "John",
        lastName: "Doe",
        email: "john.doe@example.com",
        phone: "123-456-7890",
        hireDate: "2020-01-15",
        department: "Engineering",
      },
      {
        employeeId: "E002",
        firstName: "Jane",
        lastName: "Smith",
        email: "jane.smith@example.com",
        phone: "098-765-4321",
        hireDate: "2019-03-22",
        department: "HR",
      },
      {
        employeeId: "E003",
        firstName: "Victoria",
        lastName: "Garcia",
        email: "victoria.garcia@example.com",
        phone: "789-012-3456",
        hireDate: "2020-11-25",
        department: "Marketing",
      },
      {
        employeeId: "E004",
        firstName: "William",
        lastName: "Hernandez",
        email: "william.hernandez@example.com",
        phone: "123-456-7890",
        hireDate: "2019-08-05",
        department: "Engineering",
      },
      {
        employeeId: "E005",
        firstName: "Xavier",
        lastName: "Johnson",
        email: "xavier.johnson@example.com",
        phone: "567-890-1234",
        hireDate: "2018-05-15",
        department: "HR",
      },
      {
        employeeId: "E006",
        firstName: "Yasmine",
        lastName: "King",
        email: "yasmine.king@example.com",
        phone: "901-234-5678",
        hireDate: "2021-02-28",
        department: "Marketing",
      },
      {
        employeeId: "E007",
        firstName: "Zoe",
        lastName: "Lee",
        email: "zoe.lee@example.com",
        phone: "345-678-9012",
        hireDate: "2020-09-10",
        department: "Engineering",
      },
      {
        employeeId: "E008",
        firstName: "Adam",
        lastName: "Miller",
        email: "adam.miller@example.com",
        phone: "789-012-3456",
        hireDate: "2019-06-20",
        department: "HR",
      },
      {
        employeeId: "E009",
        firstName: "Bella",
        lastName: "Nelson",
        email: "bella.nelson@example.com",
        phone: "123-456-7890",
        hireDate: "2018-03-01",
        department: "Marketing",
      },
      {
        employeeId: "E010",
        firstName: "Caleb",
        lastName: "O'Connor",
        email: "caleb.oconnor@example.com",
        phone: "567-890-1234",
        hireDate: "2021-01-10",
        department: "Engineering",
      },
      {
        employeeId: "E011",
        firstName: "Daniel",
        lastName: "Parker",
        email: "daniel.parker@example.com",
        phone: "901-234-5678",
        hireDate: "2020-08-15",
        department: "HR",
      },
      {
        employeeId: "E012",
        firstName: "Emma",
        lastName: "Quinn",
        email: "emma.quinn@example.com",
        phone: "345-678-9012",
        hireDate: "2019-05-25",
        department: "Marketing",
      },
    ],
  },
  {
    id: 2,
    table_name: "Customer Data Table",
    table_definition: {
      columns: [
        {
          id: 1,
          name: "customerId",
          type: "text",
          header: "Customer ID",
          filter: true,
          sortable: true,
        },
        {
          id: 2,
          name: "firstName",
          type: "text",
          header: "First Name",
          filter: true,
          sortable: true,
        },
        {
          id: 3,
          name: "lastName",
          type: "text",
          header: "Last Name",
          filter: true,
          sortable: true,
        },
        {
          id: 4,
          name: "email",
          type: "email",
          header: "Email",
          filter: true,
          sortable: true,
        },
        {
          id: 5,
          name: "phone",
          type: "text",
          header: "Phone Number",
          filter: true,
          sortable: true,
        },
        {
          id: 6,
          name: "registrationDate",
          type: "date",
          header: "Registration Date",
          filter: true,
          sortable: true,
        },
        {
          id: 7,
          name: "membership",
          type: "text",
          header: "Membership Type",
          filter: true,
          sortable: true,
        },
        { id: 8, name: "actions", type: "actions", header: "Actions" },
      ],
    },
    data: [
      {
        customerId: "C001",
        firstName: "Alice",
        lastName: "Brown",
        email: "alice.brown@example.com",
        phone: "321-654-9870",
        registrationDate: "2018-07-30",
        membership: "Gold",
      },
      {
        customerId: "C002",
        firstName: "Bob",
        lastName: "White",
        email: "bob.white@example.com",
        phone: "789-012-3456",
        registrationDate: "2019-11-11",
        membership: "Silver",
      },
      {
        customerId: "C003",
        firstName: "Charlie",
        lastName: "Green",
        email: "charlie@example.com",
        phone: "456-789-0123",
        registrationDate: "2020-02-29",
        membership: "Platinum",
      },
      {
        customerId: "C004",
        firstName: "David",
        lastName: "Lee",
        email: "david.lee@example.com",
        phone: "987-654-3210",
        registrationDate: "2021-05-20",
        membership: "Bronze",
      },
      {
        customerId: "C005",
        firstName: "Emily",
        lastName: "Johnson",
        email: "emily.johnson@example.com",
        phone: "567-890-1234",
        registrationDate: "2020-12-01",
        membership: "Silver",
      },
      {
        customerId: "C006",
        firstName: "Frank",
        lastName: "Davis",
        email: "frank.davis@example.com",
        phone: "234-567-8901",
        registrationDate: "2019-06-10",
        membership: "Gold",
      },
      {
        customerId: "C007",
        firstName: "Grace",
        lastName: "Wilson",
        email: "grace.wilson@example.com",
        phone: "890-123-4567",
        registrationDate: "2018-03-05",
        membership: "Platinum",
      },
      {
        customerId: "C008",
        firstName: "Henry",
        lastName: "Anderson",
        email: "henry.anderson@example.com",
        phone: "456-789-0123",
        registrationDate: "2021-01-15",
        membership: "Bronze",
      },
      {
        customerId: "C009",
        firstName: "Isabella",
        lastName: "Martinez",
        email: "isabella.martinez@example.com",
        phone: "901-234-5678",
        registrationDate: "2020-08-20",
        membership: "Silver",
      },
      {
        customerId: "C010",
        firstName: "Jacob",
        lastName: "Taylor",
        email: "jacob.taylor@example.com",
        phone: "345-678-9012",
        registrationDate: "2019-04-01",
        membership: "Gold",
      },
      {
        customerId: "C011",
        firstName: "Katherine",
        lastName: "Clark",
        email: "katherine.clark@example.com",
        phone: "789-012-3456",
        registrationDate: "2018-11-10",
        membership: "Platinum",
      },
      {
        customerId: "C012",
        firstName: "Liam",
        lastName: "Lewis",
        email: "liam.lewis@example.com",
        phone: "123-456-7890",
        registrationDate: "2021-02-25",
        membership: "Bronze",
      },
      {
        customerId: "C013",
        firstName: "Mia",
        lastName: "Harris",
        email: "mia.harris@example.com",
        phone: "567-890-1234",
        registrationDate: "2020-09-05",
        membership: "Silver",
      },
      {
        customerId: "C014",
        firstName: "Noah",
        lastName: "Martin",
        email: "noah.martin@example.com",
        phone: "901-234-5678",
        registrationDate: "2019-05-15",
        membership: "Gold",
      },
      {
        customerId: "C015",
        firstName: "Olivia",
        lastName: "Thompson",
        email: "olivia.thompson@example.com",
        phone: "345-678-9012",
        registrationDate: "2018-02-28",
        membership: "Platinum",
      },
      {
        customerId: "C016",
        firstName: "Patrick",
        lastName: "Walker",
        email: "patrick.walker@example.com",
        phone: "789-012-3456",
        registrationDate: "2021-03-10",
        membership: "Bronze",
      },
      {
        customerId: "C017",
        firstName: "Quinn",
        lastName: "Allen",
        email: "quinn.allen@example.com",
        phone: "123-456-7890",
        registrationDate: "2020-10-20",
        membership: "Silver",
      },
      {
        customerId: "C018",
        firstName: "Ryan",
        lastName: "Baker",
        email: "ryan.baker@example.com",
        phone: "567-890-1234",
        registrationDate: "2019-06-01",
        membership: "Gold",
      },
      {
        customerId: "C019",
        firstName: "Sophia",
        lastName: "Carter",
        email: "sophia.carter@example.com",
        phone: "901-234-5678",
        registrationDate: "2018-01-10",
        membership: "Platinum",
      },
      {
        customerId: "C020",
        firstName: "Thomas",
        lastName: "Edwards",
        email: "thomas.edwards@example.com",
        phone: "345-678-9012",
        registrationDate: "2021-04-15",
        membership: "Bronze",
      },
    ],
  },
  {
    id: 3,
    table_name: "Product Inventory",
    table_definition: {
      columns: [
        {
          id: 1,
          name: "productId",
          type: "text",
          header: "Product ID",
          filter: true,
          sortable: true,
        },
        {
          id: 2,
          name: "productName",
          type: "text",
          header: "Product Name",
          filter: true,
          sortable: true,
        },
        {
          id: 3,
          name: "category",
          type: "text",
          header: "Category",
          filter: true,
          sortable: true,
        },
        {
          id: 4,
          name: "price",
          type: "number",
          header: "Price",
          filter: true,
          sortable: true,
        },
        {
          id: 5,
          name: "stock",
          type: "number",
          header: "Stock",
          filter: true,
          sortable: true,
        },
        {
          id: 6,
          name: "supplier",
          type: "text",
          header: "Supplier",
          filter: true,
          sortable: true,
        },
      ],
    },
    data: [
      {
        productId: "P001",
        productName: "Laptop",
        category: "Electronics",
        price: 1200,
        stock: 50,
        supplier: "Supplier A",
      },
      {
        productId: "P002",
        productName: "Chair",
        category: "Furniture",
        price: 150,
        stock: 200,
        supplier: "Supplier B",
      },
      {
        productId: "P003",
        productName: "Shampoo",
        category: "Groceries",
        price: 10,
        stock: 100,
        supplier: "Supplier C",
      },
      {
        productId: "P004",
        productName: "Phone",
        category: "Electronics",
        price: 800,
        stock: 80,
        supplier: "Supplier A",
      },
      {
        productId: "P005",
        productName: "Table",
        category: "Furniture",
        price: 300,
        stock: 30,
        supplier: "Supplier B",
      },
      //generate 20 more values
      {
        productId: "P006",
        productName: "Tablet",
        category: "Electronics",
        price: 500,
        stock: 40,
        supplier: "Supplier A",
      },
      {
        productId: "P007",
        productName: "Sofa",
        category: "Furniture",
        price: 700,
        stock: 20,
        supplier: "Supplier B",
      },
      {
        productId: "P008",
        productName: "Soap",
        category: "Groceries",
        price: 5,
        stock: 150,
        supplier: "Supplier C",
      },
      {
        productId: "P009",
        productName: "Camera",
        category: "Electronics",
        price: 1000,
        stock: 60,
        supplier: "Supplier A",
      },
      {
        productId: "P010",
        productName: "Bed",
        category: "Furniture",
        price: 1000,
        stock: 10,
        supplier: "Supplier B",
      },
      {
        productId: "P011",
        productName: "Shirt",
        category: "Clothing",
        price: 20,
        stock: 300,
        supplier: "Supplier D",
      },
      {
        productId: "P012",
        productName: "Pants",
        category: "Clothing",
        price: 30,
        stock: 200,
        supplier: "Supplier E",
      },
      {
        productId: "P013",
        productName: "Hat",
        category: "Accessories",
        price: 10,
        stock: 100,
        supplier: "Supplier F",
      },
      {
        productId: "P014",
        productName: "Sunglasses",
        category: "Accessories",
        price: 15,
        stock: 150,
        supplier: "Supplier G",
      },
      {
        productId: "P015",
        productName: "Watch",
        category: "Accessories",
        price: 50,
        stock: 80,
        supplier: "Supplier H",
      },
      {
        productId: "P016",
        productName: "Headphones",
        category: "Electronics",
        price: 100,
        stock: 120,
        supplier: "Supplier I",
      },
      {
        productId: "P017",
        productName: "Keyboard",
        category: "Electronics",
        price: 50,
        stock: 90,
        supplier: "Supplier J",
      },
      {
        productId: "P018",
        productName: "Mouse",
        category: "Electronics",
        price: 20,
        stock: 150,
        supplier: "Supplier K",
      },
      {
        productId: "P019",
        productName: "Monitor",
        category: "Electronics",
        price: 200,
        stock: 70,
        supplier: "Supplier L",
      },
      {
        productId: "P020",
        productName: "Printer",
        category: "Electronics",
        price: 150,
        stock: 60,
        supplier: "Supplier M",
      },
    ],
  },
  {
    id: 4,
    table_name: "Order Management",
    table_definition: {
      columns: [
        {
          id: 1,
          name: "orderId",
          type: "text",
          header: "Order ID",
          filter: true,
          sortable: true,
        },
        {
          id: 2,
          name: "customerId",
          type: "text",
          header: "Customer ID",
          filter: true,
          sortable: true,
        },
        {
          id: 3,
          name: "orderDate",
          type: "date",
          header: "Order Date",
          filter: true,
          sortable: true,
        },
        {
          id: 4,
          name: "status",
          type: "text",
          header: "Status",
          filter: true,
          sortable: true,
        },
        {
          id: 5,
          name: "total",
          type: "number",
          header: "Total Amount",
          filter: true,
          sortable: true,
        },
      ],
    },
    data: [
      {
        orderId: "O001",
        customerId: "C001",
        orderDate: "2022-01-15",
        status: "Shipped",
        total: 1500,
      },
      {
        orderId: "O002",
        customerId: "C002",
        orderDate: "2022-01-20",
        status: "Pending",
        total: 200,
      },
      {
        orderId: "O003",
        customerId: "C003",
        orderDate: "2022-01-25",
        status: "Delivered",
        total: 500,
      },
      {
        orderId: "O004",
        customerId: "C004",
        orderDate: "2022-01-30",
        status: "Cancelled",
        total: 800,
      },
      {
        orderId: "O005",
        customerId: "C005",
        orderDate: "2022-02-01",
        status: "Shipped",
        total: 300,
      },
      //generate 20 more values
      {
        orderId: "O006",
        customerId: "C006",
        orderDate: "2022-02-05",
        status: "Shipped",
        total: 700,
      },
      {
        orderId: "O007",
        customerId: "C007",
        orderDate: "2022-02-10",
        status: "Pending",
        total: 1000,
      },
      {
        orderId: "O008",
        customerId: "C008",
        orderDate: "2022-02-15",
        status: "Delivered",
        total: 1200,
      },
      {
        orderId: "O009",
        customerId: "C009",
        orderDate: "2022-02-20",
        status: "Cancelled",
        total: 1500,
      },
      {
        orderId: "O010",
        customerId: "C010",
        orderDate: "2022-02-25",
        status: "Shipped",
        total: 2000,
      },
      {
        orderId: "O011",
        customerId: "C011",
        orderDate: "2022-03-01",
        status: "Shipped",
        total: 2500,
      },
      {
        orderId: "O012",
        customerId: "C012",
        orderDate: "2022-03-05",
        status: "Pending",
        total: 3000,
      },
      {
        orderId: "O013",
        customerId: "C013",
        orderDate: "2022-03-10",
        status: "Delivered",
        total: 3500,
      },
      {
        orderId: "O014",
        customerId: "C014",
        orderDate: "2022-03-15",
        status: "Cancelled",
        total: 4000,
      },
      {
        orderId: "O015",
        customerId: "C015",
        orderDate: "2022-03-20",
        status: "Shipped",
        total: 4500,
      },
      {
        orderId: "O016",
        customerId: "C016",
        orderDate: "2022-03-25",
        status: "Shipped",
        total: 5000,
      },
      {
        orderId: "O017",
        customerId: "C017",
        orderDate: "2022-03-30",
        status: "Pending",
        total: 5500,
      },
    ],
  },
  {
    id: 5,
    table_name: "Sales Records",
    table_definition: {
      columns: [
        {
          id: 1,
          name: "saleId",
          type: "text",
          header: "Sale ID",
          filter: true,
          sortable: true,
        },
        {
          id: 2,
          name: "productId",
          type: "text",
          header: "Product ID",
          filter: true,
          sortable: true,
        },
        {
          id: 3,
          name: "saleDate",
          type: "date",
          header: "Sale Date",
          filter: true,
          sortable: true,
        },
        {
          id: 4,
          name: "quantity",
          type: "number",
          header: "Quantity",
          filter: true,
          sortable: true,
        },
        {
          id: 5,
          name: "totalPrice",
          type: "number",
          header: "Total Price",
          filter: true,
          sortable: true,
        },
      ],
    },
    data: [
      {
        saleId: "S001",
        productId: "P001",
        saleDate: "2022-01-15",
        quantity: 10,
        totalPrice: 12000,
      },
      {
        saleId: "S002",
        productId: "P002",
        saleDate: "2022-01-20",
        quantity: 5,
        totalPrice: 750,
      },
      {
        saleId: "S003",
        productId: "P003",
        saleDate: "2022-01-25",
        quantity: 20,
        totalPrice: 200,
      },
      {
        saleId: "S004",
        productId: "P004",
        saleDate: "2022-01-30",
        quantity: 8,
        totalPrice: 6400,
      },
      {
        saleId: "S005",
        productId: "P005",
        saleDate: "2022-02-01",
        quantity: 3,
        totalPrice: 900,
      },
      //generate 20 more values
      {
        saleId: "S006",
        productId: "P006",
        saleDate: "2022-02-05",
        quantity: 15,
        totalPrice: 7500,
      },
      {
        saleId: "S007",
        productId: "P007",
        saleDate: "2022-02-10",
        quantity: 25,
        totalPrice: 1250,
      },
      {
        saleId: "S008",
        productId: "P008",
        saleDate: "2022-02-15",
        quantity: 30,
        totalPrice: 300,
      },
      {
        saleId: "S009",
        productId: "P009",
        saleDate: "2022-02-20",
        quantity: 18,
        totalPrice: 14400,
      },
      {
        saleId: "S010",
        productId: "P010",
        saleDate: "2022-02-25",
        quantity: 5,
        totalPrice: 1500,
      },
      {
        saleId: "S011",
        productId: "P011",
        saleDate: "2022-03-01",
        quantity: 12,
        totalPrice: 240,
      },
      {
        saleId: "S012",
        productId: "P012",
        saleDate: "2022-03-05",
        quantity: 22,
        totalPrice: 6600,
      },
      {
        saleId: "S013",
        productId: "P013",
        saleDate: "2022-03-10",
        quantity: 7,
        totalPrice: 70,
      },
      {
        saleId: "S014",
        productId: "P014",
        saleDate: "2022-03-15",
        quantity: 9,
        totalPrice: 135,
      },
      {
        saleId: "S015",
        productId: "P015",
        saleDate: "2022-03-20",
        quantity: 2,
        totalPrice: 100,
      },
      {
        saleId: "S016",
        productId: "P016",
        saleDate: "2022-03-25",
        quantity: 14,
        totalPrice: 1400,
      },
      {
        saleId: "S017",
        productId: "P017",
        saleDate: "2022-03-30",
        quantity: 10,
        totalPrice: 100,
      },
    ],
  },
  {
    id: 6,
    table_name: "Supplier Information",
    table_definition: {
      columns: [
        {
          id: 1,
          name: "supplierId",
          type: "text",
          header: "Supplier ID",
          filter: true,
          sortable: true,
        },
        {
          id: 2,
          name: "supplierName",
          type: "text",
          header: "Supplier Name",
          filter: true,
          sortable: true,
        },
        {
          id: 3,
          name: "contact",
          type: "text",
          header: "Contact",
          filter: true,
          sortable: true,
        },
        {
          id: 4,
          name: "email",
          type: "email",
          header: "Email",
          filter: true,
          sortable: true,
        },
        {
          id: 5,
          name: "phone",
          type: "text",
          header: "Phone",
          filter: true,
          sortable: true,
        },
        {
          id: 6,
          name: "address",
          type: "text",
          header: "Address",
          filter: true,
          sortable: true,
        },
      ],
    },
    data: [
      {
        supplierId: "S001",
        supplierName: "Supplier A",
        contact: "John Doe",
        email: "john.doe@supplierA.com",
        phone: "123-456-7890",
        address: "123 Main St",
      },
      {
        supplierId: "S002",
        supplierName: "Supplier B",
        contact: "Jane Smith",
        email: "jane.smith@supplierB.com",
        phone: "098-765-4321",
        address: "456 Elm St",
      },
      {
        supplierId: "S003",
        supplierName: "Supplier C",
        contact: "Jim Brown",
        email: "jim.brown@supplierC.com",
        phone: "567-890-1234",
        address: "789 Pine St",
      },
      {
        supplierId: "S004",
        supplierName: "Supplier D",
        contact: "Jack Johnson",
        email: "jack.johnson@supplierD.com",
        phone: "234-567-8901",
        address: "101 Maple St",
      },
      {
        supplierId: "S005",
        supplierName: "Supplier E",
        contact: "Jill Davis",
        email: "jill.davis@supplierE.com",
        phone: "890-123-4567",
        address: "202 Oak St",
      },
      {
        supplierId: "S006",
        supplierName: "Supplier F",
        contact: "Frank White",
        email: "frank.davis@supplierF.com",
        phone: "901-234-5678",
        address: "303 Walnut St",
      },
      {
        supplierId: "S007",
        supplierName: "Supplier G",
        contact: "Grace Wilson",
        email: "george.wilson@supplierF.com",
        phone: "345-678-9012",
        address: "404 Cedar St",
      },
    ],
  },
  {
    id: 7,
    table_name: "Project Management",
    table_definition: {
      columns: [
        {
          id: 1,
          name: "projectId",
          type: "text",
          header: "Project ID",
          filter: true,
          sortable: true,
        },
        {
          id: 2,
          name: "projectName",
          type: "text",
          header: "Project Name",
          filter: true,
          sortable: true,
        },
        {
          id: 3,
          name: "startDate",
          type: "date",
          header: "Start Date",
          filter: true,
          sortable: true,
        },
        {
          id: 4,
          name: "endDate",
          type: "date",
          header: "End Date",
          filter: true,
          sortable: true,
        },
        {
          id: 5,
          name: "status",
          type: "text",
          header: "Status",
          filter: true,
          sortable: true,
        },
        {
          id: 6,
          name: "budget",
          type: "number",
          header: "Budget",
          filter: true,
          sortable: true,
        },
      ],
    },
    data: [
      {
        projectId: "P001",
        projectName: "Project Alpha",
        startDate: "2022-01-01",
        endDate: "2022-12-31",
        status: "Ongoing",
        budget: 100000,
      },
      {
        projectId: "P002",
        projectName: "Project Beta",
        startDate: "2022-02-01",
        endDate: "2022-10-31",
        status: "Ongoing",
        budget: 50000,
      },
      {
        projectId: "P003",
        projectName: "Project Gamma",
        startDate: "2022-03-01",
        endDate: "2022-09-30",
        status: "Completed",
        budget: 75000,
      },
      {
        projectId: "P004",
        projectName: "Project Delta",
        startDate: "2022-04-01",
        endDate: "2022-08-31",
        status: "Ongoing",
        budget: 60000,
      },
      {
        projectId: "P005",
        projectName: "Project Epsilon",
        startDate: "2022-05-01",
        endDate: "2022-11-30",
        status: "Ongoing",
        budget: 80000,
      },
      {
        projectId: "P006",
        projectName: "Project Zeta",
        startDate: "2022-06-01",
        endDate: "2022-12-31",
        status: "Planned",
        budget: 95000,
      },
      {
        projectId: "P007",
        projectName: "Project Eta",
        startDate: "2022-07-01",
        endDate: "2022-12-31",
        status: "Planned",
        budget: 105000,
      },
      {
        projectId: "P008",
        projectName: "Project Theta",
        startDate: "2022-08-01",
        endDate: "2022-12-31",
        status: "Ongoing",
        budget: 110000,
      },
      {
        projectId: "P009",
        projectName: "Project Iota",
        startDate: "2022-09-01",
        endDate: "2023-01-31",
        status: "Ongoing",
        budget: 120000,
      },
      {
        projectId: "P010",
        projectName: "Project Kappa",
        startDate: "2022-10-01",
        endDate: "2023-02-28",
        status: "Ongoing",
        budget: 130000,
      },
      {
        projectId: "P011",
        projectName: "Project Lambda",
        startDate: "2022-11-01",
        endDate: "2023-03-31",
        status: "Ongoing",
        budget: 140000,
      },
      {
        projectId: "P012",
        projectName: "Project Mu",
        startDate: "2022-12-01",
        endDate: "2023-04-30",
        status: "Ongoing",
        budget: 150000,
      },
      {
        projectId: "P013",
        projectName: "Project Nu",
        startDate: "2023-01-01",
        endDate: "2023-05-31",
        status: "Planned",
        budget: 160000,
      },
      {
        projectId: "P014",
        projectName: "Project Xi",
        startDate: "2023-02-01",
        endDate: "2023-06-30",
        status: "Planned",
        budget: 170000,
      },
      {
        projectId: "P015",
        projectName: "Project Omicron",
        startDate: "2023-03-01",
        endDate: "2023-07-31",
        status: "Planned",
        budget: 180000,
      },
      {
        projectId: "P016",
        projectName: "Project Pi",
        startDate: "2023-04-01",
        endDate: "2023-08-31",
        status: "Planned",
        budget: 190000,
      },
      {
        projectId: "P017",
        projectName: "Project Rho",
        startDate: "2023-05-01",
        endDate: "2023-09-30",
        status: "Planned",
        budget: 200000,
      },
      {
        projectId: "P018",
        projectName: "Project Sigma",
        startDate: "2023-06-01",
        endDate: "2023-10-31",
        status: "Planned",
        budget: 210000,
      },
      {
        projectId: "P019",
        projectName: "Project Tau",
        startDate: "2023-07-01",
        endDate: "2023-11-30",
        status: "Planned",
        budget: 220000,
      },
      {
        projectId: "P020",
        projectName: "Project Upsilon",
        startDate: "2023-08-01",
        endDate: "2023-12-31",
        status: "Planned",
        budget: 230000,
      },
      {
        projectId: "P021",
        projectName: "Project Phi",
        startDate: "2023-09-01",
        endDate: "2024-01-31",
        status: "Planned",
        budget: 240000,
      },
      {
        projectId: "P022",
        projectName: "Project Chi",
        startDate: "2023-10-01",
        endDate: "2024-02-29",
        status: "Planned",
        budget: 250000,
      },
      {
        projectId: "P023",
        projectName: "Project Psi",
        startDate: "2023-11-01",
        endDate: "2024-03-31",
        status: "Planned",
        budget: 260000,
      },
      {
        projectId: "P024",
        projectName: "Project Omega",
        startDate: "2023-12-01",
        endDate: "2024-04-30",
        status: "Planned",
        budget: 270000,
      },
      {
        projectId: "P025",
        projectName: "Project Alpha II",
        startDate: "2024-01-01",
        endDate: "2024-05-31",
        status: "Planned",
        budget: 280000,
      },
      {
        projectId: "P026",
        projectName: "Project Beta II",
        startDate: "2024-02-01",
        endDate: "2024-06-30",
        status: "Planned",
        budget: 290000,
      },
      {
        projectId: "P027",
        projectName: "Project Gamma II",
        startDate: "2024-03-01",
        endDate: "2024-07-31",
        status: "Planned",
        budget: 300000,
      },
      {
        projectId: "P028",
        projectName: "Project Delta II",
        startDate: "2024-04-01",
        endDate: "2024-08-31",
        status: "Planned",
        budget: 310000,
      },
      {
        projectId: "P029",
        projectName: "Project Epsilon II",
        startDate: "2024-05-01",
        endDate: "2024-09-30",
        status: "Planned",
        budget: 320000,
      },
      {
        projectId: "P030",
        projectName: "Project Zeta II",
        startDate: "2024-06-01",
        endDate: "2024-10-31",
        status: "Planned",
        budget: 330000,
      },
      {
        projectId: "P031",
        projectName: "Project Eta II",
        startDate: "2024-07-01",
        endDate: "2024-11-30",
        status: "Planned",
        budget: 340000,
      },
      {
        projectId: "P032",
        projectName: "Project Theta II",
        startDate: "2024-08-01",
        endDate: "2024-12-31",
        status: "Planned",
        budget: 350000,
      },
      {
        projectId: "P033",
        projectName: "Project Iota II",
        startDate: "2024-09-01",
        endDate: "2025-01-31",
        status: "Planned",
        budget: 360000,
      },
      {
        projectId: "P034",
        projectName: "Project Kappa II",
        startDate: "2024-10-01",
        endDate: "2025-02-28",
        status: "Planned",
        budget: 370000,
      },
      {
        projectId: "P035",
        projectName: "Project Lambda II",
        startDate: "2024-11-01",
        endDate: "2025-03-31",
        status: "Planned",
        budget: 380000,
      },
      {
        projectId: "P036",
        projectName: "Project Mu II",
        startDate: "2024-12-01",
        endDate: "2025-04-30",
        status: "Planned",
        budget: 390000,
      },
      {
        projectId: "P037",
        projectName: "Project Nu II",
        startDate: "2025-01-01",
        endDate: "2025-05-31",
        status: "Planned",
        budget: 400000,
      },
      {
        projectId: "P038",
        projectName: "Project Xi II",
        startDate: "2025-02-01",
        endDate: "2025-06-30",
        status: "Planned",
        budget: 410000,
      },
      {
        projectId: "P039",
        projectName: "Project Omicron II",
        startDate: "2025-03-01",
        endDate: "2025-07-31",
        status: "Planned",
        budget: 420000,
      },
      {
        projectId: "P040",
        projectName: "Project Pi II",
        startDate: "2025-04-01",
        endDate: "2025-08-31",
        status: "Planned",
        budget: 430000,
      },
      {
        projectId: "P041",
        projectName: "Project Rho II",
        startDate: "2025-05-01",
        endDate: "2025-09-30",
        status: "Planned",
        budget: 440000,
      },
      {
        projectId: "P042",
        projectName: "Project Sigma II",
        startDate: "2025-06-01",
        endDate: "2025-10-31",
        status: "Planned",
        budget: 450000,
      },
      {
        projectId: "P043",
        projectName: "Project Tau II",
        startDate: "2025-07-01",
        endDate: "2025-11-30",
        status: "Planned",
        budget: 460000,
      },
      {
        projectId: "P044",
        projectName: "Project Upsilon II",
        startDate: "2025-08-01",
        endDate: "2025-12-31",
        status: "Planned",
        budget: 470000,
      },
      {
        projectId: "P045",
        projectName: "Project Phi II",
        startDate: "2025-09-01",
        endDate: "2026-01-31",
        status: "Planned",
        budget: 480000,
      },
      {
        projectId: "P046",
        projectName: "Project Chi II",
        startDate: "2025-10-01",
        endDate: "2026-02-28",
        status: "Planned",
        budget: 490000,
      },
      {
        projectId: "P047",
        projectName: "Project Psi II",
        startDate: "2025-11-01",
        endDate: "2026-03-31",
        status: "Planned",
        budget: 500000,
      },
      {
        projectId: "P048",
        projectName: "Project Omega II",
        startDate: "2025-12-01",
        endDate: "2026-04-30",
        status: "Planned",
        budget: 510000,
      },
      {
        projectId: "P049",
        projectName: "Project Alpha III",
        startDate: "2026-01-01",
        endDate: "2026-05-31",
        status: "Planned",
        budget: 520000,
      },
      {
        projectId: "P050",
        projectName: "Project Beta III",
        startDate: "2026-02-01",
        endDate: "2026-06-30",
        status: "Planned",
        budget: 530000,
      },
      {
        projectId: "P051",
        projectName: "Project Gamma III",
        startDate: "2026-03-01",
        endDate: "2026-07-31",
        status: "Planned",
        budget: 540000,
      },
      {
        projectId: "P052",
        projectName: "Project Delta III",
        startDate: "2026-04-01",
        endDate: "2026-08-31",
        status: "Planned",
        budget: 550000,
      },
      {
        projectId: "P053",
        projectName: "Project Epsilon III",
        startDate: "2026-05-01",
        endDate: "2026-09-30",
        status: "Planned",
        budget: 560000,
      },
      {
        projectId: "P054",
        projectName: "Project Zeta III",
        startDate: "2026-06-01",
        endDate: "2026-10-31",
        status: "Planned",
        budget: 570000,
      },
      {
        projectId: "P055",
        projectName: "Project Eta III",
        startDate: "2026-07-01",
        endDate: "2026-11-30",
        status: "Planned",
        budget: 580000,
      },
      {
        projectId: "P056",
        projectName: "Project Theta III",
        startDate: "2026-08-01",
        endDate: "2026-12-31",
        status: "Planned",
        budget: 590000,
      },
      {
        projectId: "P057",
        projectName: "Project Iota III",
        startDate: "2026-09-01",
        endDate: "2027-01-31",
        status: "Planned",
        budget: 600000,
      },
      {
        projectId: "P058",
        projectName: "Project Kappa III",
        startDate: "2026-10-01",
        endDate: "2027-02-28",
        status: "Planned",
        budget: 610000,
      },
      {
        projectId: "P059",
        projectName: "Project Lambda III",
        startDate: "2026-11-01",
        endDate: "2027-03-31",
        status: "Planned",
        budget: 620000,
      },
      {
        projectId: "P060",
        projectName: "Project Mu III",
        startDate: "2026-12-01",
        endDate: "2027-04-30",
        status: "Planned",
        budget: 630000,
      },
      {
        projectId: "P061",
        projectName: "Project Nu III",
        startDate: "2027-01-01",
        endDate: "2027-05-31",
        status: "Planned",
        budget: 640000,
      },
      {
        projectId: "P062",
        projectName: "Project Xi III",
        startDate: "2027-02-01",
        endDate: "2027-06-30",
        status: "Planned",
        budget: 650000,
      },
      {
        projectId: "P063",
        projectName: "Project Omicron III",
        startDate: "2027-03-01",
        endDate: "2027-07-31",
        status: "Planned",
        budget: 660000,
      },
      {
        projectId: "P064",
        projectName: "Project Pi III",
        startDate: "2027-04-01",
        endDate: "2027-08-31",
        status: "Planned",
        budget: 670000,
      },
      {
        projectId: "P065",
        projectName: "Project Rho III",
        startDate: "2027-05-01",
        endDate: "2027-09-30",
        status: "Planned",
        budget: 680000,
      },
      {
        projectId: "P066",
        projectName: "Project Sigma III",
        startDate: "2027-06-01",
        endDate: "2027-10-31",
        status: "Planned",
        budget: 690000,
      },
      {
        projectId: "P067",
        projectName: "Project Tau III",
        startDate: "2027-07-01",
        endDate: "2027-11-30",
        status: "Planned",
        budget: 700000,
      },
      {
        projectId: "P068",
        projectName: "Project Upsilon III",
        startDate: "2027-08-01",
        endDate: "2027-12-31",
        status: "Planned",
        budget: 710000,
      },
    ],
  },
  {
    id: 8,
    table_name: "Event Calendar",
    table_definition: {
      columns: [
        {
          id: 1,
          name: "eventId",
          type: "text",
          header: "Event ID",
          filter: true,
          sortable: true,
        },
        {
          id: 2,
          name: "eventName",
          type: "text",
          header: "Event Name",
          filter: true,
          sortable: true,
        },
        {
          id: 3,
          name: "date",
          type: "date",
          header: "Date",
          filter: true,
          sortable: true,
        },
        {
          id: 4,
          name: "location",
          type: "text",
          header: "Location",
          filter: true,
          sortable: true,
        },
        {
          id: 5,
          name: "organizer",
          type: "text",
          header: "Organizer",
          filter: true,
          sortable: true,
        },
      ],
    },
    data: [
      {
        eventId: "E001",
        eventName: "Tech Conference",
        date: "2022-03-15",
        location: "New York",
        organizer: "Tech Corp",
      },
      {
        eventId: "E002",
        eventName: "Music Festival",
        date: "2022-04-20",
        location: "Los Angeles",
        organizer: "Music Inc",
      },
      {
        eventId: "E003",
        eventName: "Art Exhibition",
        date: "2022-05-25",
        location: "Chicago",
        organizer: "Art World",
      },
      {
        eventId: "E004",
        eventName: "Food Expo",
        date: "2022-06-30",
        location: "San Francisco",
        organizer: "Foodies",
      },
      {
        eventId: "E005",
        eventName: "Business Summit",
        date: "2022-07-10",
        location: "Miami",
        organizer: "Biz Group",
      },
      {
        eventId: "E006",
        eventName: "Fashion Show",
        date: "2022-08-15",
        location: "New York",
        organizer: "Fashion Co",
      },
      {
        eventId: "E007",
        eventName: "Film Festival",
        date: "2022-09-20",
        location: "Los Angeles",
        organizer: "Film Studio",
      },
      {
        eventId: "E008",
        eventName: "Sports Event",
        date: "2022-10-25",
        location: "Chicago",
        organizer: "Sports Club",
      },
      {
        eventId: "E009",
        eventName: "Book Fair",
        date: "2022-11-30",
        location: "San Francisco",
        organizer: "Book Store",
      },
      {
        eventId: "E010",
        eventName: "Health Expo",
        date: "2022-12-05",
        location: "Miami",
        organizer: "Health Co",
      },
      {
        eventId: "E011",
        eventName: "Tech Conference II",
        date: "2023-01-10",
        location: "New York",
        organizer: "Tech Corp",
      },
      {
        eventId: "E012",
        eventName: "Music Festival II",
        date: "2023-02-15",
        location: "Los Angeles",
        organizer: "Music Inc",
      },
      {
        eventId: "E013",
        eventName: "Art Exhibition II",
        date: "2023-03-20",
        location: "Chicago",
        organizer: "Art World",
      },
      {
        eventId: "E014",
        eventName: "Food Expo II",
        date: "2023-04-25",
        location: "San Francisco",
        organizer: "Foodies",
      },
      {
        eventId: "E015",
        eventName: "Business Summit II",
        date: "2023-05-30",
        location: "Miami",
        organizer: "Biz Group",
      },
      {
        eventId: "E016",
        eventName: "Fashion Show II",
        date: "2023-06-05",
        location: "New York",
        organizer: "Fashion Co",
      },
      {
        eventId: "E017",
        eventName: "Film Festival II",
        date: "2023-07-10",
        location: "Los Angeles",
        organizer: "Film Studio",
      },
      {
        eventId: "E018",
        eventName: "Sports Event II",
        date: "2023-08-15",
        location: "Chicago",
        organizer: "Sports Club",
      },
      {
        eventId: "E019",
        eventName: "Book Fair II",
        date: "2023-09-20",
        location: "San Francisco",
        organizer: "Book Store",
      },
      {
        eventId: "E020",
        eventName: "Health Expo II",
        date: "2023-10-25",
        location: "Miami",
        organizer: "Health Co",
      },
      {
        eventId: "E021",
        eventName: "Tech Conference III",
        date: "2023-11-30",
        location: "New York",
        organizer: "Tech Corp",
      },
      {
        eventId: "E022",
        eventName: "Music Festival III",
        date: "2023-12-05",
        location: "Los Angeles",
        organizer: "Music Inc",
      },
      {
        eventId: "E023",
        eventName: "Art Exhibition III",
        date: "2024-01-10",
        location: "Chicago",
        organizer: "Art World",
      },
      {
        eventId: "E024",
        eventName: "Food Expo III",
        date: "2024-02-15",
        location: "San Francisco",
        organizer: "Foodies",
      },
      {
        eventId: "E025",
        eventName: "Business Summit III",
        date: "2024-03-20",
        location: "Miami",
        organizer: "Biz Group",
      },
      {
        eventId: "E026",
        eventName: "Fashion Show III",
        date: "2024-04-25",
        location: "New York",
        organizer: "Fashion Co",
      },
      {
        eventId: "E027",
        eventName: "Film Festival III",
        date: "2024-05-30",
        location: "Los Angeles",
        organizer: "Film Studio",
      },
      {
        eventId: "E028",
        eventName: "Sports Event III",
        date: "2024-06-05",
        location: "Chicago",
        organizer: "Sports Club",
      },
      {
        eventId: "E029",
        eventName: "Book Fair III",
        date: "2024-07-10",
        location: "San Francisco",
        organizer: "Book Store",
      },
    ],
  },
  {
    id: 9,
    table_name: "Training Programs",
    table_definition: {
      columns: [
        {
          id: 1,
          name: "programId",
          type: "text",
          header: "Program ID",
          filter: true,
          sortable: true,
        },
        {
          id: 2,
          name: "programName",
          type: "text",
          header: "Program Name",
          filter: true,
          sortable: true,
        },
        {
          id: 3,
          name: "startDate",
          type: "date",
          header: "Start Date",
          filter: true,
          sortable: true,
        },
        {
          id: 4,
          name: "endDate",
          type: "date",
          header: "End Date",
          filter: true,
          sortable: true,
        },
        {
          id: 5,
          name: "trainer",
          type: "text",
          header: "Trainer",
          filter: true,
          sortable: true,
        },
        {
          id: 6,
          name: "location",
          type: "text",
          header: "Location",
          filter: true,
          sortable: true,
        },
      ],
    },
    data: [
      {
        programId: "T001",
        programName: "Leadership Training",
        startDate: "2022-01-10",
        endDate: "2022-01-20",
        trainer: "John Doe",
        location: "New York",
      },
      {
        programId: "T002",
        programName: "Sales Training",
        startDate: "2022-02-15",
        endDate: "2022-02-25",
        trainer: "Jane Smith",
        location: "Los Angeles",
      },
      {
        programId: "T003",
        programName: "Tech Skills",
        startDate: "2022-03-05",
        endDate: "2022-03-15",
        trainer: "Jim Brown",
        location: "Chicago",
      },
      {
        programId: "T004",
        programName: "Customer Service",
        startDate: "2022-04-10",
        endDate: "2022-04-20",
        trainer: "Jack Johnson",
        location: "San Francisco",
      },
      {
        programId: "T005",
        programName: "Project Management",
        startDate: "2022-05-15",
        endDate: "2022-05-25",
        trainer: "Jill Davis",
        location: "Miami",
      },
    ],
  },
  {
    id: 10,
    table_name: "Vendor Contacts",
    table_definition: {
      columns: [
        {
          id: 1,
          name: "vendorId",
          type: "text",
          header: "Vendor ID",
          filter: true,
          sortable: true,
        },
        {
          id: 2,
          name: "vendorName",
          type: "text",
          header: "Vendor Name",
          filter: true,
          sortable: true,
        },
        {
          id: 3,
          name: "contactName",
          type: "text",
          header: "Contact Name",
          filter: true,
          sortable: true,
        },
        {
          id: 4,
          name: "email",
          type: "email",
          header: "Email",
          filter: true,
          sortable: true,
        },
        {
          id: 5,
          name: "phone",
          type: "text",
          header: "Phone",
          filter: true,
          sortable: true,
        },
        {
          id: 6,
          name: "address",
          type: "text",
          header: "Address",
          filter: true,
          sortable: true,
        },
      ],
    },
    data: [
      {
        vendorId: "V001",
        vendorName: "Vendor A",
        contactName: "Alice Brown",
        email: "alice.brown@vendorA.com",
        phone: "321-654-9870",
        address: "123 Main St",
      },
      {
        vendorId: "V002",
        vendorName: "Vendor B",
        contactName: "Bob White",
        email: "bob.white@vendorB.com",
        phone: "789-012-3456",
        address: "456 Elm St",
      },
      {
        vendorId: "V003",
        vendorName: "Vendor C",
        contactName: "Charlie Green",
        email: "charlie.green@vendorC.com",
        phone: "456-789-0123",
        address: "789 Pine St",
      },
      {
        vendorId: "V004",
        vendorName: "Vendor D",
        contactName: "David Lee",
        email: "david.lee@vendorD.com",
        phone: "987-654-3210",
        address: "101 Maple St",
      },
      {
        vendorId: "V005",
        vendorName: "Vendor E",
        contactName: "Emily Johnson",
        email: "emily.johnson@vendorE.com",
        phone: "567-890-1234",
        address: "202 Oak St",
      },
    ],
  },
  {
    id: 11,
    table_name: "Expense Tracking",
    table_definition: {
      columns: [
        {
          id: 1,
          name: "expenseId",
          type: "text",
          header: "Expense ID",
          filter: true,
          sortable: true,
        },
        {
          id: 2,
          name: "date",
          type: "date",
          header: "Date",
          filter: true,
          sortable: true,
        },
        {
          id: 3,
          name: "category",
          type: "text",
          header: "Category",
          filter: true,
          sortable: true,
        },
        {
          id: 4,
          name: "amount",
          type: "number",
          header: "Amount",
          filter: true,
          sortable: true,
        },
        {
          id: 5,
          name: "description",
          type: "text",
          header: "Description",
          filter: true,
          sortable: true,
        },
      ],
    },
    data: [
      {
        expenseId: "EX001",
        date: "2022-01-01",
        category: "Travel",
        amount: 500,
        description: "Flight tickets",
      },
      {
        expenseId: "EX002",
        date: "2022-01-05",
        category: "Food",
        amount: 150,
        description: "Team lunch",
      },
      {
        expenseId: "EX003",
        date: "2022-01-10",
        category: "Office Supplies",
        amount: 200,
        description: "Stationery",
      },
      {
        expenseId: "EX004",
        date: "2022-01-15",
        category: "Travel",
        amount: 300,
        description: "Hotel booking",
      },
      {
        expenseId: "EX005",
        date: "2022-01-20",
        category: "Utilities",
        amount: 100,
        description: "Internet bill",
      },
    ],
  },
  {
    id: 12,
    table_name: "Marketing Campaigns",
    table_definition: {
      columns: [
        {
          id: 1,
          name: "campaignId",
          type: "text",
          header: "Campaign ID",
          filter: true,
          sortable: true,
        },
        {
          id: 2,
          name: "campaignName",
          type: "text",
          header: "Campaign Name",
          filter: true,
          sortable: true,
        },
        {
          id: 3,
          name: "startDate",
          type: "date",
          header: "Start Date",
          filter: true,
          sortable: true,
        },
        {
          id: 4,
          name: "endDate",
          type: "date",
          header: "End Date",
          filter: true,
          sortable: true,
        },
        {
          id: 5,
          name: "budget",
          type: "number",
          header: "Budget",
          filter: true,
          sortable: true,
        },
        {
          id: 6,
          name: "status",
          type: "text",
          header: "Status",
          filter: true,
          sortable: true,
        },
      ],
    },
    data: [
      {
        campaignId: "MC001",
        campaignName: "Spring Sale",
        startDate: "2022-03-01",
        endDate: "2022-03-31",
        budget: 10000,
        status: "Ongoing",
      },
      {
        campaignId: "MC002",
        campaignName: "Summer Discount",
        startDate: "2022-06-01",
        endDate: "2022-06-30",
        budget: 15000,
        status: "Ongoing",
      },
      {
        campaignId: "MC003",
        campaignName: "Fall Promotion",
        startDate: "2022-09-01",
        endDate: "2022-09-30",
        budget: 12000,
        status: "Planned",
      },
      {
        campaignId: "MC004",
        campaignName: "Winter Clearance",
        startDate: "2022-12-01",
        endDate: "2022-12-31",
        budget: 20000,
        status: "Planned",
      },
      {
        campaignId: "MC005",
        campaignName: "Black Friday",
        startDate: "2022-11-25",
        endDate: "2022-11-26",
        budget: 5000,
        status: "Completed",
      },
    ],
  },
  {
    id: 13,
    table_name: "Product Reviews",
    table_definition: {
      columns: [
        {
          id: 1,
          name: "reviewId",
          type: "text",
          header: "Review ID",
          filter: true,
          sortable: true,
        },
        {
          id: 2,
          name: "productId",
          type: "text",
          header: "Product ID",
          filter: true,
          sortable: true,
        },
        {
          id: 3,
          name: "customerId",
          type: "text",
          header: "Customer ID",
          filter: true,
          sortable: true,
        },
        {
          id: 4,
          name: "rating",
          type: "number",
          header: "Rating",
          filter: true,
          sortable: true,
        },
        {
          id: 5,
          name: "review",
          type: "text",
          header: "Review",
          filter: true,
          sortable: true,
        },
        {
          id: 6,
          name: "date",
          type: "date",
          header: "Date",
          filter: true,
          sortable: true,
        },
      ],
    },
    data: [
      {
        reviewId: "R001",
        productId: "P001",
        customerId: "C001",
        rating: 5,
        review: "Excellent product!",
        date: "2022-01-15",
      },
      {
        reviewId: "R002",
        productId: "P002",
        customerId: "C002",
        rating: 4,
        review: "Very good, but a bit expensive.",
        date: "2022-01-20",
      },
      {
        reviewId: "R003",
        productId: "P003",
        customerId: "C003",
        rating: 3,
        review: "Average quality.",
        date: "2022-01-25",
      },
      {
        reviewId: "R004",
        productId: "P004",
        customerId: "C004",
        rating: 5,
        review: "Highly recommend!",
        date: "2022-01-30",
      },
      {
        reviewId: "R005",
        productId: "P005",
        customerId: "C005",
        rating: 4,
        review: "Good product, fast delivery.",
        date: "2022-02-01",
      },
    ],
  },
  {
    id: 14,
    table_name: "Inventory Management",
    table_definition: {
      columns: [
        {
          id: 1,
          name: "itemId",
          type: "text",
          header: "Item ID",
          filter: true,
          sortable: true,
        },
        {
          id: 2,
          name: "itemName",
          type: "text",
          header: "Item Name",
          filter: true,
          sortable: true,
        },
        {
          id: 3,
          name: "quantity",
          type: "number",
          header: "Quantity",
          filter: true,
          sortable: true,
        },
        {
          id: 4,
          name: "location",
          type: "text",
          header: "Location",
          filter: true,
          sortable: true,
        },
        {
          id: 5,
          name: "supplier",
          type: "text",
          header: "Supplier",
          filter: true,
          sortable: true,
        },
      ],
    },
    data: [
      {
        itemId: "I001",
        itemName: "Widget A",
        quantity: 100,
        location: "Warehouse 1",
        supplier: "Supplier X",
      },
      {
        itemId: "I002",
        itemName: "Widget B",
        quantity: 200,
        location: "Warehouse 2",
        supplier: "Supplier Y",
      },
      {
        itemId: "I003",
        itemName: "Widget C",
        quantity: 150,
        location: "Warehouse 1",
        supplier: "Supplier X",
      },
      {
        itemId: "I004",
        itemName: "Widget D",
        quantity: 50,
        location: "Warehouse 3",
        supplier: "Supplier Z",
      },
      {
        itemId: "I005",
        itemName: "Widget E",
        quantity: 250,
        location: "Warehouse 2",
        supplier: "Supplier Y",
      },
    ],
  },
  {
    id: 15,
    table_name: "Task Management",
    table_definition: {
      columns: [
        {
          id: 1,
          name: "taskId",
          type: "text",
          header: "Task ID",
          filter: true,
          sortable: true,
        },
        {
          id: 2,
          name: "taskName",
          type: "text",
          header: "Task Name",
          filter: true,
          sortable: true,
        },
        {
          id: 3,
          name: "assignedTo",
          type: "text",
          header: "Assigned To",
          filter: true,
          sortable: true,
        },
        {
          id: 4,
          name: "dueDate",
          type: "date",
          header: "Due Date",
          filter: true,
          sortable: true,
        },
        {
          id: 5,
          name: "status",
          type: "text",
          header: "Status",
          filter: true,
          sortable: true,
        },
      ],
    },
    data: [
      {
        taskId: "T001",
        taskName: "Design Homepage",
        assignedTo: "Alice",
        dueDate: "2022-03-01",
        status: "In Progress",
      },
      {
        taskId: "T002",
        taskName: "Develop API",
        assignedTo: "Bob",
        dueDate: "2022-03-10",
        status: "Pending",
      },
      {
        taskId: "T003",
        taskName: "Test Application",
        assignedTo: "Charlie",
        dueDate: "2022-03-15",
        status: "Completed",
      },
      {
        taskId: "T004",
        taskName: "Deploy to Server",
        assignedTo: "David",
        dueDate: "2022-03-20",
        status: "Pending",
      },
      {
        taskId: "T005",
        taskName: "Create Documentation",
        assignedTo: "Emily",
        dueDate: "2022-03-25",
        status: "In Progress",
      },
    ],
  },
  {
    id: 16,
    table_name: "Client Information",
    table_definition: {
      columns: [
        {
          id: 1,
          name: "clientId",
          type: "text",
          header: "Client ID",
          filter: true,
          sortable: true,
        },
        {
          id: 2,
          name: "clientName",
          type: "text",
          header: "Client Name",
          filter: true,
          sortable: true,
        },
        {
          id: 3,
          name: "email",
          type: "email",
          header: "Email",
          filter: true,
          sortable: true,
        },
        {
          id: 4,
          name: "phone",
          type: "text",
          header: "Phone",
          filter: true,
          sortable: true,
        },
        {
          id: 5,
          name: "address",
          type: "text",
          header: "Address",
          filter: true,
          sortable: true,
        },
        {
          id: 6,
          name: "contactPerson",
          type: "text",
          header: "Contact Person",
          filter: true,
          sortable: true,
        },
      ],
    },
    data: [
      {
        clientId: "C001",
        clientName: "Client A",
        email: "clientA@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        contactPerson: "John Doe",
      },
      {
        clientId: "C002",
        clientName: "Client B",
        email: "clientB@example.com",
        phone: "098-765-4321",
        address: "456 Elm St",
        contactPerson: "Jane Smith",
      },
      {
        clientId: "C003",
        clientName: "Client C",
        email: "clientC@example.com",
        phone: "567-890-1234",
        address: "789 Pine St",
        contactPerson: "Jim Brown",
      },
      {
        clientId: "C004",
        clientName: "Client D",
        email: "clientD@example.com",
        phone: "234-567-8901",
        address: "101 Maple St",
        contactPerson: "Jack Johnson",
      },
      {
        clientId: "C005",
        clientName: "Client E",
        email: "clientE@example.com",
        phone: "890-123-4567",
        address: "202 Oak St",
        contactPerson: "Jill Davis",
      },
    ],
  },
  {
    id: 17,
    table_name: "Attendance Records",
    table_definition: {
      columns: [
        {
          id: 1,
          name: "recordId",
          type: "text",
          header: "Record ID",
          filter: true,
          sortable: true,
        },
        {
          id: 2,
          name: "employeeId",
          type: "text",
          header: "Employee ID",
          filter: true,
          sortable: true,
        },
        {
          id: 3,
          name: "date",
          type: "date",
          header: "Date",
          filter: true,
          sortable: true,
        },
        {
          id: 4,
          name: "status",
          type: "text",
          header: "Status",
          filter: true,
          sortable: true,
        },
      ],
    },
    data: [
      {
        recordId: "A001",
        employeeId: "E001",
        date: "2022-01-01",
        status: "Present",
      },
      {
        recordId: "A002",
        employeeId: "E002",
        date: "2022-01-01",
        status: "Absent",
      },
      {
        recordId: "A003",
        employeeId: "E003",
        date: "2022-01-01",
        status: "Present",
      },
      {
        recordId: "A004",
        employeeId: "E004",
        date: "2022-01-01",
        status: "Present",
      },
      {
        recordId: "A005",
        employeeId: "E005",
        date: "2022-01-01",
        status: "Absent",
      },
    ],
  },
  {
    id: 18,
    table_name: "Financial Transactions",
    table_definition: {
      columns: [
        {
          id: 1,
          name: "transactionId",
          type: "text",
          header: "Transaction ID",
          filter: true,
          sortable: true,
        },
        {
          id: 2,
          name: "date",
          type: "date",
          header: "Date",
          filter: true,
          sortable: true,
        },
        {
          id: 3,
          name: "amount",
          type: "number",
          header: "Amount",
          filter: true,
          sortable: true,
        },
        {
          id: 4,
          name: "type",
          type: "text",
          header: "Type",
          filter: true,
          sortable: true,
        },
        {
          id: 5,
          name: "description",
          type: "text",
          header: "Description",
          filter: true,
          sortable: true,
        },
      ],
    },
    data: [
      {
        transactionId: "T001",
        date: "2022-01-01",
        amount: 1000,
        type: "Credit",
        description: "Payment received",
      },
      {
        transactionId: "T002",
        date: "2022-01-05",
        amount: 500,
        type: "Debit",
        description: "Office supplies",
      },
      {
        transactionId: "T003",
        date: "2022-01-10",
        amount: 2000,
        type: "Credit",
        description: "Project payment",
      },
      {
        transactionId: "T004",
        date: "2022-01-15",
        amount: 1500,
        type: "Debit",
        description: "Travel expenses",
      },
      {
        transactionId: "T005",
        date: "2022-01-20",
        amount: 800,
        type: "Credit",
        description: "Service fee",
      },
    ],
  },
  {
    id: 19,
    table_name: "Support Tickets",
    table_definition: {
      columns: [
        {
          id: 1,
          name: "ticketId",
          type: "text",
          header: "Ticket ID",
          filter: true,
          sortable: true,
        },
        {
          id: 2,
          name: "customerId",
          type: "text",
          header: "Customer ID",
          filter: true,
          sortable: true,
        },
        {
          id: 3,
          name: "issue",
          type: "text",
          header: "Issue",
          filter: true,
          sortable: true,
        },
        {
          id: 4,
          name: "status",
          type: "text",
          header: "Status",
          filter: true,
          sortable: true,
        },
        {
          id: 5,
          name: "createdDate",
          type: "date",
          header: "Created Date",
          filter: true,
          sortable: true,
        },
      ],
    },
    data: [
      {
        ticketId: "TK001",
        customerId: "C001",
        issue: "Login issue",
        status: "Open",
        createdDate: "2022-01-01",
      },
      {
        ticketId: "TK002",
        customerId: "C002",
        issue: "Payment not processed",
        status: "Closed",
        createdDate: "2022-01-05",
      },
      {
        ticketId: "TK003",
        customerId: "C003",
        issue: "Account locked",
        status: "Pending",
        createdDate: "2022-01-10",
      },
      {
        ticketId: "TK004",
        customerId: "C004",
        issue: "Password reset",
        status: "Open",
        createdDate: "2022-01-15",
      },
      {
        ticketId: "TK005",
        customerId: "C005",
        issue: "Service disruption",
        status: "Closed",
        createdDate: "2022-01-20",
      },
      {
        ticketId: "TK006",
        customerId: "C006",
        issue: "Product return",
        status: "Open",
        createdDate: "2022-01-25",
      },
      {
        ticketId: "TK007",
        customerId: "C007",
        issue: "Refund request",
        status: "Pending",
        createdDate: "2022-01-30",
      },
      {
        ticketId: "TK008",
        customerId: "C008",
        issue: "Technical support",
        status: "Open",
        createdDate: "2022-02-01",
      },
      {
        ticketId: "TK009",
        customerId: "C009",
        issue: "Billing inquiry",
        status: "Closed",
        createdDate: "2022-02-05",
      },
      {
        ticketId: "TK010",
        customerId: "C010",
        issue: "Product exchange",
        status: "Open",
        createdDate: "2022-02-10",
      },
      {
        ticketId: "TK011",
        customerId: "C011",
        issue: "Order tracking",
        status: "Closed",
        createdDate: "2022-02-15",
      },
      {
        ticketId: "TK012",
        customerId: "C012",
        issue: "Technical issue",
        status: "Open",
        createdDate: "2022-02-20",
      },
      {
        ticketId: "TK013",
        customerId: "C013",
        issue: "Product repair",
        status: "Pending",
        createdDate: "2022-02-25",
      },
      {
        ticketId: "TK014",
        customerId: "C014",
        issue: "Service request",
        status: "Open",
        createdDate: "2022-03-01",
      },
      {
        ticketId: "TK015",
        customerId: "C015",
        issue: "Feedback submission",
        status: "Closed",
        createdDate: "2022-03-05",
      },
      {
        ticketId: "TK016",
        customerId: "C016",
        issue: "Complaint resolution",
        status: "Open",
        createdDate: "2022-03-10",
      },
      {
        ticketId: "TK017",
        customerId: "C017",
        issue: "Technical assistance",
        status: "Closed",
        createdDate: "2022-03-15",
      },
      {
        ticketId: "TK018",
        customerId: "C018",
        issue: "Product replacement",
        status: "Open",
        createdDate: "2022-03-20",
      },
    ],
  },
  {
    id: 20,
    table_name: "User Feedback",
    table_definition: {
      columns: [
        {
          id: 1,
          name: "feedbackId",
          type: "text",
          header: "Feedback ID",
          filter: true,
          sortable: true,
        },
        {
          id: 2,
          name: "userId",
          type: "text",
          header: "User ID",
          filter: true,
          sortable: true,
        },
        {
          id: 3,
          name: "comments",
          type: "text",
          header: "Comments",
          filter: true,
          sortable: true,
        },
        {
          id: 4,
          name: "rating",
          type: "number",
          header: "Rating",
          filter: true,
          sortable: true,
        },
        {
          id: 5,
          name: "date",
          type: "date",
          header: "Date",
          filter: true,
          sortable: true,
        },
      ],
    },
    data: [
      {
        feedbackId: "F001",
        userId: "U001",
        comments: "Great service!",
        rating: 5,
        date: "2022-01-01",
      },
      {
        feedbackId: "F002",
        userId: "U002",
        comments: "Satisfactory experience.",
        rating: 4,
        date: "2022-01-05",
      },
      {
        feedbackId: "F003",
        userId: "U003",
        comments: "Needs improvement.",
        rating: 3,
        date: "2022-01-10",
      },
      {
        feedbackId: "F004",
        userId: "U004",
        comments: "Very helpful support.",
        rating: 5,
        date: "2022-01-15",
      },
      {
        feedbackId: "F005",
        userId: "U005",
        comments: "Not satisfied.",
        rating: 2,
        date: "2022-01-20",
      },
      {
        feedbackId: "F006",
        userId: "U006",
        comments: "Excellent product!",
        rating: 5,
        date: "2022-01-25",
      },
      {
        feedbackId: "F007",
        userId: "U007",
        comments: "Fast delivery.",
        rating: 4,
        date: "2022-01-30",
      },
      {
        feedbackId: "F008",
        userId: "U008",
        comments: "Good value for money.",
        rating: 4,
        date: "2022-02-01",
      },
      {
        feedbackId: "F009",
        userId: "U009",
        comments: "Prompt service.",
        rating: 5,
        date: "2022-02-05",
      },
      {
        feedbackId: "F010",
        userId: "U010",
        comments: "User-friendly interface.",
        rating: 4,
        date: "2022-02-10",
      },
      {
        feedbackId: "F011",
        userId: "U011",
        comments: "Highly recommended!",
        rating: 5,
        date: "2022-02-15",
      },
      {
        feedbackId: "F012",
        userId: "U012",
        comments: "Great customer support.",
        rating: 5,
        date: "2022-02-20",
      },
      {
        feedbackId: "F013",
        userId: "U013",
        comments: "Quality products.",
        rating: 4,
        date: "2022-02-25",
      },
      {
        feedbackId: "F014",
        userId: "U014",
        comments: "Timely delivery.",
        rating: 5,
        date: "2022-03-01",
      },
      {
        feedbackId: "F015",
        userId: "U015",
        comments: "Professional service.",
        rating: 5,
        date: "2022-03-05",
      },
      {
        feedbackId: "F016",
        userId: "U016",
        comments: "Impressive performance.",
        rating: 4,
        date: "2022-03-10",
      },
      {
        feedbackId: "F017",
        userId: "U017",
        comments: "Good experience overall.",
        rating: 4,
        date: "2022-03-15",
      },
      {
        feedbackId: "F018",
        userId: "U018",
        comments: "Responsive support team.",
        rating: 5,
        date: "2022-03-20",
      },
      {
        feedbackId: "F019",
        userId: "U019",
        comments: "Excellent service!",
        rating: 5,
        date: "2022-03-25",
      },
      {
        feedbackId: "F020",
        userId: "U020",
        comments: "Highly satisfied.",
        rating: 5,
        date: "2022-04-01",
      },
      {
        feedbackId: "F021",
        userId: "U021",
        comments: "Great value for money.",
        rating: 4,
        date: "2022-04-05",
      },
      {
        feedbackId: "F022",
        userId: "U022",
        comments: "Professional team.",
        rating: 5,
        date: "2022-04-10",
      },
      {
        feedbackId: "F023",
        userId: "U023",
        comments: "Prompt response.",
        rating: 4,
        date: "2022-04-15",
      },
      {
        feedbackId: "F024",
        userId: "U024",
        comments: "Excellent quality products.",
        rating: 5,
        date: "2022-04-20",
      },
      {
        feedbackId: "F025",
        userId: "U025",
        comments: "Fast shipping.",
        rating: 4,
        date: "2022-04-25",
      },
      {
        feedbackId: "F026",
        userId: "U026",
        comments: "User-friendly platform.",
        rating: 5,
        date: "2022-05-01",
      },
      {
        feedbackId: "F027",
        userId: "U027",
        comments: "Great customer service.",
        rating: 5,
        date: "2022-05-05",
      },
      {
        feedbackId: "F028",
        userId: "U028",
        comments: "Highly recommend!",
        rating: 5,
        date: "2022-05-10",
      },
      {
        feedbackId: "F029",
        userId: "U029",
        comments: "Excellent experience.",
        rating: 4,
        date: "2022-05-15",
      },
      {
        feedbackId: "F030",
        userId: "U030",
        comments: "Professional service.",
        rating: 5,
        date: "2022-05-20",
      },
      {
        feedbackId: "F031",
        userId: "U031",
        comments: "Quality products.",
        rating: 4,
        date: "2022-05-25",
      },
      {
        feedbackId: "F032",
        userId: "U032",
        comments: "Timely delivery.",
        rating: 5,
        date: "2022-06-01",
      },
      {
        feedbackId: "F033",
        userId: "U033",
        comments: "Responsive support team.",
        rating: 5,
        date: "2022-06-05",
      },
      {
        feedbackId: "F034",
        userId: "U034",
        comments: "Excellent service!",
        rating: 5,
        date: "2022-06-10",
      },
    ],
  },
];
