name: "🎉 Deploy website"

on:
  workflow_run:
    workflows: ["🧪 Build and Test"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          run-id: ${{ github.event.workflow_run.id }}

      - name: "📂 Sync files pascu.io"
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 92.205.1.205
          username: ${{ secrets.ftp_username_1 }}
          password: ${{ secrets.ftp_password_1 }}
          port: 21
          local-dir: build
          server-dir: /public_html/
          timeout: 60000
