on:
  push:
    branches:
      - main


name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:

      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.lock') }}

      - name: Install packages
        run: yarn install

      - name: 🔨 Build Project
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

        run: yarn run build-production

      - name: 📂 Sync files pascu.io
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 92.205.1.205
          username: ${{ secrets.ftp_username_1 }}
          password: ${{ secrets.ftp_password_1 }}
          port: 21
          local-dir: ./build/
          server-dir: /public_html/
          timeout: 60000